version: '3'
services:

  db:
    restart: always
    image: mysql:5.7
    networks:
      - internal_network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql/data

  memcached:
    image: memcached:1.5.10-alpine

  web:
    image: naari3/lazylist
    restart: always
    environment:
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET_KEY: ${TWITTER_CONSUMER_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      MEMCACHE_URL: ${MEMCACHE_URL}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      RAILS_ENV: production
    command: bash -c "rm -f /app/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - memcached

networks:
  external_network:
  internal_network:
    internal: true
